name: Checkov

on:
  workflow_call:

permissions: read-all

jobs:
  scan:
    name: Checkov
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # permissions:
    #   contents: read
    #   security-events: write
    #   actions: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: results.sarif
