name: tfsec

on:
  workflow_call:
    env:
      WORKING_DIRECTORY:
        required: true

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Terraform Security Scan
        uses: triat/terraform-security-scan@v3
        with:
          tfsec_actions_working_dir: ${{ env.WORKING_DIRECTORY }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
