name: 'Terraform State Lock'
description: 'Manage Terraform state locks'

inputs:
  TERRAFORM_VERSION:
    description: 'Terraform version to use'
    required: true
  WORKING_DIRECTORY:
    description: 'Directory containing Terraform files'
    required: true
  LOCK_ID:
    description: 'Terraform lock ID'
    required: true
  AWS_ACCESS_KEY_ID:
    description: 'AWS Access Key ID'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS Secret Access Key'
    required: true
  AWS_ENDPOINT_URL_S3:
    description: 'AWS S3 endpoint URL'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.TERRAFORM_VERSION }}

    - name: Terraform Init
      shell: bash
      run: terraform init -no-color
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_ENDPOINT_URL_S3: ${{ inputs.AWS_ENDPOINT_URL_S3 }}

    - name: Terraform State Lock
      shell: bash
      run: terraform force-unlock -force -no-color ${{ inputs.LOCK_ID }}
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      env:
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        AWS_ENDPOINT_URL_S3: ${{ inputs.AWS_ENDPOINT_URL_S3 }}
