name: 'Set up VPN'
description: 'Configure WireGuard VPN connection using linuxserver/wireguard'

inputs:
  WG_CONFIG_FILE:
    description: 'WireGuard configuration file'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create WireGuard configuration
      steps:
        - run: |
              sudo apt install resolvconf
              sudo apt install wireguard
              echo "${{ inputs.WG_CONFIG_FILE }}" > wg0.conf
              sudo chmod 600 wg0.conf
              echo "setting config"
              sudo wg-quick up ./wg0.conf
          shell: bash

    - name: Test VPN Connection
      shell: bash
      run: |
        # Testar conectividade com ping
        echo "Testando conectividade com ping..."
        ping -c 5 10.100.0.250

        # Testar conectividade com curl
        echo "Testando conectividade com curl..."
        curl -s https://pve.home.viniciusgoncalves.com
