name: 'Set up VPN'
description: 'Configure WireGuard VPN connection using native WireGuard'

inputs:
  WG_CONFIG_FILE:
    description: 'WireGuard configuration file'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create WireGuard configuration
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y resolvconf wireguard
        echo "${{ inputs.WG_CONFIG_FILE }}" > wg0.conf
        sudo chmod 600 wg0.conf
        echo "Setting up WireGuard configuration"
        sudo wg-quick up ./wg0.conf

    - name: Test VPN Connection
      shell: bash
      run: |
        # Testar conectividade com ping
        echo "Testando conectividade com ping..."
        ping -c 5 10.100.0.250

        # Testar conectividade com curl
        echo "Testando conectividade com curl..."
        curl -s https://pve.home.viniciusgoncalves.com
