name: 'Set up VPN'
description: 'Configure WireGuard VPN connection'

inputs:
  WG_CONFIG_FILE:
    description: 'WireGuard configuration file'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up WireGuard Connection
      uses: niklaskeerl/easy-wireguard-action@v2
      with:
        WG_CONFIG_FILE: ${{ inputs.WG_CONFIG_FILE }}
        
    - name: Test curl public IP
      shell: bash
      run: curl https://www.google.com
      
    - name: Test ping private IP
      shell: bash
      run: ping -c 5 10.100.0.250
      
    - name: Test curl private IP dns
      shell: bash
      run: curl https://pve.home.viniciusgoncalves.com