name: 'Set up VPN'
description: 'Configure WireGuard VPN connection'

inputs:
  WG_CONFIG_FILE:
    description: 'WireGuard configuration file'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up WireGuard Connection
      uses: niklaskeerl/easy-wireguard-action@v2
      with:
        WG_CONFIG_FILE: ${{ inputs.WG_CONFIG_FILE }}
