name: Terraform Apply

on:
  push:
    branches:
      - main

env:
  TF_VAR_endpoint: ${{ secrets.TF_PVE_PROVIDER_ENDPOINT }}
  TF_VAR_api_token: ${{ secrets.TF_PVE_PROVIDER_API_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
  TERRAFORM_VERSION: ~1.12
  WORKING_DIRECTORY: ./terraform


jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: terraform init -no-color
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Terraform Apply
        run: terraform apply -no-color
        working-directory: ${{ env.WORKING_DIRECTORY }}
