name: Push

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: ./.github/actions/security/checkov

  tfsec-scan:
    name: TFSec Scan
    runs-on: ubuntu-latest
    timeout-minutes: 5
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: ./.github/actions/security/tfsec
        with:
          WORKING_DIRECTORY: ./terraform

  terraform-apply:
    name: Terraform Apply
    needs: [security-scan, tfsec-scan]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up VPN
        uses: ./.github/actions/security/vpn
        with:
          WG_CONFIG_FILE: ${{ secrets.WG_CONFIG_FILE }}
      - uses: ./.github/actions/terraform/apply
        with:
          TERRAFORM_VERSION: ~1.12
          WORKING_DIRECTORY: ./terraform
          TF_VAR_endpoint: ${{ secrets.TF_PVE_PROVIDER_ENDPOINT }}
          TF_VAR_api_token: ${{ secrets.TF_PVE_PROVIDER_API_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
