name: tfsec

on:
  # push:
  #   branches: [ "main", "master" ]
  # pull_request:
  #   branches: [ "main", "master" ]

  workflow_dispatch:

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Security Scan
        uses: triat/terraform-security-scan@v3
        with:
          tfsec_actions_working_dir: ${{ env.WORKING_DIRECTORY }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
