name: Set up VPN

on:
  workflow_dispatch:

jobs:
  wireguard:
    name: Set up VPN
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - uses: ./.github/actions/security/vpn
        with:
          WG_CONFIG_FILE: ${{ secrets.WG_CONFIG_FILE }}

      - name: Test ping private IP
        shell: bash
        run: ping -c 5 10.100.0.250

      - name: Test curl private IP dns
        shell: bash
        run: curl https://pve.home.viniciusgoncalves.com

